# Change these first
owner: kkehrer # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Keey
    url: https://keey.ch
  - name: TXgroup
    url: https://tx.group
  - name: Ecoreal
    url: https://www.ecoreal.ch
  - name: Bitowl
    url: https://bitowl.ch
  - name: PixelPirat
    url: https://pixelpirat.ch
  - name: Bartsch-Consulting
    url: https://www.bartsch-consulting.ch
  - name: TanDem
    url: https://tan-dem.co
  - name: Wellenreiter
    url: https://www.wellenreiter.consulting
  - name: Cavedelorge
    url: https://cavedelorge.ch
  - name: Goldhahn
    url: https://goldhahn.swiss
  - name: StudioPM
    url: https://studiopm.ch
  - name: Seilers-Werbeblog
    url: https://www.seilers-werbeblog.ch
  - name: Sakartwelo
    url: https://www.sakartwelo.com
  - name: Scharlachrot
    url: https://scharlachrot.ch
  - name: WSchneider
    url: https://www.wschneider.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.pixelpirat.ch
  # baseUrl: /your-repo-name
  name: Upptime-Tracker
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data of some of my websites.
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  incidentCommentSummary: Posted at $DATE
  navGitHub: GitHub
  footer: This page is open source, powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
